config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root "tasks#index"

  resources :tasks

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :show, :destroy]

  namespace :api do
    resources :tasks, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_wrapper/task.rb
module DataWrapper
  class Task
    attr_reader :data

    def initialize(data)
      @data = HashWithIndifferentAccess.new(data)
    end

    def id
      data[:id]
    end

    def description
      data[:description]
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :description, presence: true
  validates :description, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password
end

app/controllers/api/tasks_controller.rb
module Api
  class TasksController < ApplicationController
    def index
      @tasks = Task.all
      render json: @tasks
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to new_session_path, alert: "Not authorised" if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "You have logged in!"
    else
      flash[:notice] = "Email or password is invalid"
      render :new
    end
  end

  def show
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have logged out!"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorize, only: [:new]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.create(task_params)
    
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy!

    redirect_to root_path
  end

private

  def task_params
    params.require(:task).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: "You have successfully signed up!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionItems</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if flash[:notice] %>
     <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |form| %>
  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
    <% @task.errors.full_messages_for(:description).each do |task| %>
      <div><%= task %></div>
      <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
<% end %>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <a href="/tasks/<%= task.id %>">
        <%= task.description %>
    </li>
  <% end %>
</ul>

<% if logged_in? %>
  <%= link_to 'Add New Task', new_task_path %>
<% end %>

<% if current_user %>
  Logged in as <%= current_user.email %>
  <%= link_to 'Log Out', session_path(current_user.id) %>
<% else %>
  <%= link_to 'Sign Up', new_user_path %>
  <%= link_to 'Log In', new_session_path %>
<% end %>

app/views/tasks/new.html.erb
<h1>Add a New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Index Page', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.description %></h1>

<ul>
  <li><%= link_to 'Delete', "/tasks/#{@task.id}", method: :delete, data: { confirm: "Are you sure?" } %></li>
  <li><%= link_to "Edit", "/tasks/#{@task.id}/edit" %></li>
</ul>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <%= render 'error_messages' %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>

    <%= form.label :email %><br>
    <%= form.email_field :email %><br>

    <%= form.label :password %><br>
    <%= form.password_field :password %><br>

    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation  %><br>
  </div>

  <div>
    <%= form.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Create an Account</h1>

<%= render 'form', user: @user %>